#' Congressional district overlap matrices
#'
#' A nested list of overlap matrices used to match congressional districts
#' across consecutive redistricting cycles.
#'
#' @format A named list keyed by variable (`"pop"`, `"area"`, `"afact_s2t"`,
#'   `"afact_t2s"`, `"afact_s2t_area"`, `"afact_t2s_area"`). Each variable is a
#'   named list keyed by congress pair (e.g. `"cd111_cd112"`), covering every
#'   consecutive pair from congress 92 through 119, and each congress pair is
#'   a named list keyed by state abbreviation (e.g. `"AL"`), holding a matrix
#'   with source districts as rows and target districts as columns.
#' @source Generated by the redistrict-preprocessing pipeline; full replication materials will be deposited upon publication.
"overlap"

#' Incumbent-to-incumbent district matches
#'
#' Congressional district pairs across consecutive redistricting cycles where
#' the same person served as the incumbent in both congresses ("I2I").
#'
#' @format A data.frame with columns:
#' \describe{
#'   \item{incumbent_from}{District the incumbent represented before this redistricting cycle.}
#'   \item{incumbent_to}{District the incumbent represented (or ran in) after this redistricting cycle.}
#'   \item{cycle}{Congress pair, e.g. `"cd111_cd112"`.}
#' }
#' @source Generated by the redistrict-preprocessing pipeline; full replication materials will be deposited upon publication.
"incumbency_matches_i2i"

#' Incumbent-to-candidate district matches
#'
#' Congressional district pairs across consecutive redistricting cycles where
#' an incumbent ran for the district in the general election, excluding
#' districts where two incumbents ran against each other in a general election.
#'
#' @format A data.frame with columns:
#' \describe{
#'   \item{incumbent_from}{District the incumbent represented before this redistricting cycle.}
#'   \item{incumbent_to}{District the incumbent represented (or ran in) after this redistricting cycle.}
#'   \item{cycle}{Congress pair, e.g. `"cd111_cd112"`.}
#' }
#' @source Generated by the redistrict-preprocessing pipeline; full replication materials will be deposited upon publication.
"incumbency_matches_i2c"

